### ISSUE TITLE
Adjust the react code to testing/production instead of testnet

### ISSUE THREAD

**Issue by jjos2372** [signum-network/signum-pool#21]
Current code and comments on the react part are misleading with the "testnet" vs "mainnet" thing.

I believe it will be better described and "testing" and "production", on the "testing" mode it will use a remote pool server (which can be mainnet or testnet).

**Comment by ipr0310** [comment]
Launched a PR, updating the readme.md
https://github.com/signum-network/signum-pool/pull/22

**Comment by jjos2372** [comment]
Fixed on #22
