### ISSUE TITLE
Caused by: signumj.entity.response.http.BRSError: BRS returned error code 5: Unknown account

### ISSUE THREAD

**Issue by SpyTVofficial** [signum-network/signum-pool#40]
Caused by: signumj.entity.response.http.BRSError: BRS returned error code 5: Unknown account

**Comment by jjos2372** [comment]
Hello, your pool account must exist on the blockchain before you can operate it. Make sure your pool account (the one you set the passphrase on the config file) has made a transaction before starting it.
