### ISSUE TITLE
error fetching pools reward recipients

### ISSUE THREAD

**Issue by SpyTVofficial** [signum-network/signum-pool#42]
2021-07-15 16:23:10.637 [ERROR] [main] Pool - Error fetching pool's reward recipients or transfering from secondary pools
retrofit2.adapter.rxjava2.HttpException: HTTP 405 Method Not Alloweds

![image](https://user-images.githubusercontent.com/47456516/125804433-091dfd6b-2688-4ffa-8a86-820ad43d3e18.png)

**Comment by jjos2372** [comment]
Can you access the node you are using from the machine running the pool? Are they on the same machine?

**Comment by SpyTVofficial** [comment]
> Can you access the node you are using from the machine running the pool? Are they on the same machine?

yes they are on the same machine

**Comment by pir8radio** [comment]
hope this comment doesnt re-open the closed ticket..   but you have the wrong url in your pool config...  you prob entered the P2P url/port   you should be doing the wallet url/port.
