### ISSUE TITLE
Return 404 status code

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-pool#60]
No found pages which returns 404 to users, seems to return 200 code to search engine crawlers.
https://stackoverflow.com/questions/36052604/how-to-let-react-router-respond-with-404-status-code

**Comment by pir8radio** [comment]
I was just coming to do this as we discussed lol,  thanks for entering it! 😀

**Comment by ipr0310** [comment]
New version of React Router does not have the ``status`` prop anymore. closing the issue...
Also as react works only client-side, so the server will always return a ``200`` code because it is just serving the index file
![image](https://user-images.githubusercontent.com/35440957/153991293-e1c87651-17cc-4126-a9de-e0f1cf9a2f27.png)
