### ISSUE TITLE
Feature Request: Allow the pool to display "Worker Names"

### ISSUE THREAD

**Issue by Valareos** [signum-network/signum-pool#67]
Sometimes, people have multiple machines mining to the same addresses. It would be great that the mining pool recognizes "Worker ID" information sent by miners, so a person can see which machines are providing what mining amount. It would make it easier to see if there is  a problem with a specific machine.

**Comment by ipr0310** [comment]
This ticket is related to the following one: https://github.com/signum-network/signum-pool/issues/44
