### ISSUE TITLE
Parameters in pool.properties are being ignored.

### ISSUE THREAD

**Issue by Nivok-Spilkommen** [signum-network/signum-pool#73]
'site.homeFirstLine =' and 'site.homeSecondLine ='  no longer have any effect.  Looks like the welcome messages are now hard coded and a recompile of the HTML is required, why?

**Comment by ipr0310** [comment]
They're hardcoded in json files because of ``Multilanguage`` purposes, so you will be able to provide the message and also translate them to all available languages!

@jjos2372 you can delete these 2 props

**Comment by ipr0310** [comment]
The props have been deleted: https://github.com/signum-network/signum-pool/commit/c9f7f44e3ce30679207a0933ca573d586abf0b60
