### ISSUE TITLE
Signum pool address

### ISSUE THREAD

**Issue by BalazsGit** [signum-network/signum-pool#75]
Both [http://openburstpool.ddns.net:8126](http://openburstpool.ddns.net:8126) and [http://opensignumpool.ddns.net:8126](http://opensignumpool.ddns.net:8126) are valid and point to the same address, but better use [http://opensignumpool.ddns.net:8126](http://opensignumpool.ddns.net:8126) on the README.md file because of the rebrand.

**Comment by ipr0310** [comment]
Fixed, https://github.com/signum-network/signum-pool/commit/10e5d263f2c7304ee03ebb307a4fd078d19c8c67
