### ISSUE TITLE
Feature Request: Miner should be able to change rewards thresholds with XT Wallet

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-pool#86]
Allow the miner of a pool set/update basic pool options, using the XT Wallet
![image](https://user-images.githubusercontent.com/35440957/184517648-72b55d09-1fa7-4536-b3f5-2bf13795ed59.png)

**Comment by map1336** [comment]
It is quite rare for miners to modify these settings, as they typically view it as a one-time configuration. Additionally, miners seldom switch mining pools, making the need for frequent adjustments even less common
