### ISSUE TITLE
Issue getting pool page showing

### ISSUE THREAD

**Issue by easye35** [signum-network/signum-pool#99]
![image](https://github.com/signum-network/signum-pool/assets/11009400/b23bd48f-fc12-4edf-810e-f00e5c370758)
That is the only thing I can get to show after installing. Unbuntu 22.04, apache and ngix(tried both) java 18

Am I missing something?

**Comment by ipr0310** [comment]
It seems there is some data that maybe you did not fill up properly on `pool.properties` file
Make sure you have filled in properly `pool.properties` file and comply with the following requirements:
https://github.com/signum-network/signum-pool#requirements

If you require further clarification or have doubts, I highly recommend going to the official Signum Discord platform.
There are pool operators that could offer you help:
https://discord.gg/6zNbdxn4wK

I will be concluding this ticket as it does not pertain to a critical bug that significantly impedes the signum pool's functionality.
